name: redesign_ir
description: Redesign Imposto de Renda

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/receita_federal.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

        # - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 800
        # - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo/Arvo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Arvo/Arvo-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Arvo/Arvo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arvo/Arvo-BoldItalic.ttf
          weight: 700
          style: italic
